### PR TITLE
Lucidfind 378 modify template view new2

### PR DESCRIPTION
**Pull request by xiaoyehhuang**
I mainly did three things in these code. 
1 show author more nicely
2 make content less verbose
    a. added in every doc of data.response.docs an attribute called shortbody, which is a short version of body
    b. added in every data.highlighting[doc.id] an attribute called shortbody, which is a short version of body
Having both a and b may be inefficient in that it equals doing the same shortening process twice for every shown data. However, since they are indexed in two different ways(one is indexed by doc.id, one is indexed by numbers from 0), it seems not easy to do it much more efficiently. 

For the shortening, the basic idea is splitting the string into arrays, and then moving from the beginning and evaluating a slice of the array, that is, counting how many key words is included. The output should be the snippet with the most key words. Parameter ‘skip’ is used to control the speed of the searching. It means how many elements to skip after evaluating one slice of the array. The length of the snippet should be the ideal length to be shown in the view. It is controlled by parameter snippetLen. 

3 removed parenthesis like ‘[JIRA]’ in subjects to make it look better(only for mailing list)

### CODE REVIEW

**Comment by xiaoyehhuang** [comment]
screen shot 2016-06-01 at 5 01 52 pm

**Comment by gsingers** [comment]
@xiaoyehhuang For 2.b, I think the highlighted content is already "short" in that Solr's highlighter returns a configurable snippet of text. (google solr highlighting and look in our query pipeline for details)

I think there are 3 cases we have:
1. Display when a user first visits the site and the default query is `*` (i.e. match all docs)
2. User gives a query and there are highlighted results
3. User gives a query and there are not highlighted results

The main two to handle and shorten, I think are 1. and 3.  I don't think you need to do any additional work to highlight the words beyond what Solr gives us.

**Comment by xiaoyehhuang** [comment]
screen shot 2016-06-02 at 3 32 47 pm
screen shot 2016-06-02 at 3 32 51 pm

**Comment by xiaoyehhuang** [comment]
@gsingers 
I. For fixing the view
For the three cases:
1. Display when a user first visits the site and the default query is \* (i.e. match all docs)
2. User gives a query and there are highlighted results
3. User gives a query and there are not highlighted results

I deleted the 'shortbody' in data.highlighting[doc.id] so now for case 2, it displays the snippet solr provides. 
For case 1 and case 3, what is displayed would be that in data.response.docs.shortbody. There is one problem I have not solved:
When it is in case 1, since queryObject['q'] = '*' , what my code actually does is to find a piece which contains the most '*', which is obviously not what we want. It is quite easy to write code to have it always show the beginning when queryObject['q']=='*', but there may be other problems whenever what users search is regex expression.. I guess using regex matching can solve this problem, however, solr and javascript's syntax for regex matching maybe a little different, then it cannot automatically match.. What do you think about this problem?

II. For adding the toggle
My current solution is to always retrieve from data.response.docs.body, no matter which case of the three it is(so no highlight here). I have thought that maybe we may choose not to provide the toggle when it is already full text, but the full text preserves all the spaces so it may still be good to see even when it is already full text. 

And please let me know if anything else need to be fixed.

**Comment by xiaoyehhuang** [comment]
The newest version trims text by length based on number of characters, as opposed to length of space splitted array. It may look better since the overall length wouldn't be influenced by some very very long strings without space. And also, when the searching term is *, it will show the beginning of a text.

**Comment by gsingers** [comment]
@xiaoyehhuang Coming along nicely! 

A few things:
1. Change "full content/hide" to be "Read More/Read Less"
2. Make the Button just be an <a href> link tag.  Look in the Admin Search UI for an example (ping me if you aren't sure what this means)
3. Make the Read More/Less tag be at the bottom right of the text (again, see the Admin search UI
4. I think instead of doing all the string manipulation and creating new fields, just keep the originals, but _show_ less of them.  This will speed things up and greatly simplify the code.

**Comment by gsingers** [comment]
Fixed on other issues and in View.

**Pull request closed without merging**
