### PR TITLE
issue #30: add sign up/login

### PR DESCRIPTION
**Pull request by Pthinker**

### CODE REVIEW

**Comment by gsingers** [comment]
@Pthinker can you update this to the latest master?

**Comment by Pthinker** [comment]
@gsingers I pushed latest registration code. Can you take a look?

**Comment by gsingers** [comment]
@Pthinker Overall looks pretty good.  A couple of comments:
1. Let's confirm password and make sure it has minimum length.  Perhaps there is a good library for checking password strength?
2. After one logs in, let's change the menu to have logout button and remove the registration button.

I'll add some boilerplate text/imagery to the registration and login screen.

One question: do you know how the Snowplow Set User functionality interacts w/ the Snowplow "setUserIdFromCookie" functionality?  In other words, will we get both values (so that we can associate the UUID user id with the new registration id?

**Comment by Pthinker** [comment]
@gsingers My understanding is that snowplow will not associate UUID and registration id. Once user register/login, the track id changes on the fly and it lose track of previous id.

**Comment by gsingers** [comment]
@Pthinker ok, that should be fine.

**Comment by Pthinker** [comment]
@gsingers I have updated the pull request based on your inputs. Please check.

**Pull request merged**
